name: Node.js CI

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2

    - name: Set TimeZone for Nodejs environment
      uses: szenius/set-timezone@v1.0
      with:
          timezoneLinux: 'Asia/Bangkok'


    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
            
    - run: npm ci
    - run: npm run start
    
    - name: Commit and push if data changed
      run: |-
        git diff
        git config --global user.email "sctnightcore.bot@users.noreply.github.com"
        git config --global user.name "sctnightcore_bot"
        git add data/member.json
        git commit -m "Refresh member.json" || exit 0
        git push
