name: Scraper Worker
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
            node-version: 16

      - name: Install Dependencies
        run: npm i

      - name: Clone Data
        run: |
          git clone -b data --single-branch https://github.com/cmru-pca/scraper.git data
          mv data/data/** data && rm -rf data/data/

      - name: Run Script
        run: npm run start:tsm

      - name: Update 'data' branch
        run: |
          git checkout --orphan data
          git ls-files | grep -v '^data/' | xargs git rm -rf
          rm -rf node_modules/
          mv data/** .
          git add . && git diff
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Refresh Scraper Data" || exit 0
          git push --set-upstream origin data -f
